# Generated by Selenium IDE

# DAHA ÖNCEKİ test_saucedemo.py DOSYAMIZDA MANUEL KENDİMİZİN LOCATORLARINI BULUP YAPTIĞIMIZ KODLARI SELENIUM IDE SAYESİNDE KOLAY BİR ŞEKİLDE HAZIR YAPMIŞ OLUYORUZ.
#ÜZERİNDE DEĞİŞİKLER YAPILABİLİR ÖRN: window_size klasik maximize_window() ŞEKLİNE ÇEVİRMEK BİZE AİT VEYE URL İ GLOBALCONSTANTSTAN ÇEKEBİLİRİZ.
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from constants import globalConstants as c

class TestValidlogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_validlogin(self):
    self.driver.get(c.BASE_URL)
    self.driver.set_window_size(1552, 840)
    # username eklenecek
    self.driver.find_element(By.ID, "user-name").click()
    self.driver.find_element(By.ID, "user-name").send_keys("standard_user")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("secret_sauce")
    self.driver.find_element(By.XPATH, "//input[@id=\'login-button\']").click()
    self.driver.close()
  
